### ISSUE TITLE
PHPUnit reports warnings

### ISSUE THREAD

**Issue by nitro2010-zz** [moodleuulm/moodle-local_resort_courses#1]
In file localib.php please fix to: 

```
if(!empty($config->skipcategories)){
    $skipcategories = explode(',', $config->skipcategories);
    if (is_array($skipcategories)) {
        if (in_array($category->id, $skipcategories)) {
            return true; // Category has to be skipped -> let's return and leave the category unsorted
        }
    }

}
``
beacuse reports a lot of warnings:

```

EDebugging: Exception encountered in event observer 'resort_courses': Undefined property: stdClass::$skipcategories
- line 64 of /local/resort_courses/locallib.php: call to PHPUnit_Util_ErrorHandler::handleError()
- line ? of unknownfile: call to resort_courses()
- line 155 of /lib/classes/event/manager.php: call to call_user_func()
- line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
- line 721 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
- line 2583 of /course/lib.php: call to core\event\base->trigger()
- line 383 of /lib/testing/generator/data_generator.php: call to create_course()
- line 359 of /lib/tests/datalib_test.php: call to testing_data_generator->create_course()
- line ? of unknownfile: call to core_datalib_testcase->test_get_coursemodule_from_id()
- line 988 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php: call to ReflectionMethod->invokeArgs()
- line 838 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php: call to PHPUnit_Framework_TestCase->runTest()
- line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit_Framework_TestCase->runBare()
- line 648 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestResult.php: call to advanced_testcase->runBare()
- line 783 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php: call to PHPUnit_Framework_TestResult->run()
- line 779 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php: call to PHPUnit_Framework_TestCase->run()
- line 749 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->runTest()
- line 709 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
- line 709 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
- line 350 of /vendor/phpunit/phpunit/PHPUnit/TextUI/TestRunner.php: call to PHPUnit_Framework_TestSuite->run()
- line 176 of /vendor/phpunit/phpunit/PHPUnit/TextUI/Command.php: call to PHPUnit_TextUI_TestRunner->doRun()
- line 129 of /vendor/phpunit/phpunit/PHPUnit/TextUI/Command.php: call to PHPUnit_TextUI_Command->run()
- line 63 of /vendor/phpunit/phpunit/composer/bin/phpunit: call to PHPUnit_TextUI_Command::main()

```
```

**Comment by abias** [comment]
Thanks for this report. I hope to be able to look at this issue soon.

**Comment by abias** [comment]
Sorry for the big delay for this issue. I have finally added your patch to the plugin.

Thanks,
Alex
