### ISSUE TITLE
It's not sorted yet.

### ISSUE THREAD

**Issue by ozaza123456789** [moodleuulm/moodle-local_resort_courses#2]
They skip all of my categories. I can't choose it.

**Comment by Kathrin84** [comment]
Hi @ozaza123456789,

thank you for raising this issue. We would like to have a look at this, but your information is so minimal, we do not know where to start.

Would you please provide some more information like
* What version of the plugin do you use
* What Moodle version
* Could you provide some steps to reproduce
* Add some screenshots

Best, Kathrin

**Comment by ozaza123456789** [comment]
the plugin version is 3.2.
My moodle version is 3.2.9.
I unzip the file then add it on a local directory. The web told me that It's installed successfully.
![image](https://user-images.githubusercontent.com/51870242/63249246-467ba480-c293-11e9-91c4-482ba51f0708.png)
I can't choose to not skip categories. It still doesn't sort what I choose.

**Comment by abias** [comment]
Hi @ozaza123456789 ,

1. In your screenshot, I can see that you have selected one category to be skipped. If this was done by mistake and you want to de-select this category item, you have to hold down the control (ctrl) key on Windows or the command key on Mac and click the selected category again. This is standard behaviour of HTML multiselect widgets and nothing special to this plugin.

2. You have written that you use Moodle 3.2 with plugin version 3.2. Please be aware that neither Moodle Core 3.2 (see https://docs.moodle.org/dev/Releases#Moodle_3.2) nor the plugin version 3.2 (see https://github.com/moodleuulm/moodle-local_resort_courses#moodle-release-support) is supported anymore.

I will close this issue now. If you encounter any problems with the latest plugin version on a supported Moodle version, please let us know again.

Cheers,
Alex
