### ISSUE TITLE
Moodle 37 throws notice Undefined property: stdClass::$visible

### ISSUE THREAD

**Issue by pkgh** [moodleuulm/moodle-local_resort_courses#3]
I have successfully installed the plugin on Moodle 3.7.1. 
However, the debugger throws this whenever re-sorting is triggered:

Notice: Undefined property: stdClass::$visible in ...\course\classes\category.php on line 677

It's just a notice, but apparently something is not compatible with Moodle 37* .

**Comment by Kathrin84** [comment]
Hello @pkgh,

thank you for raising this issue.

I've already addressed this issue with a patch, but we did not yet had time to integrate it into the master branch. This will happen soon and then we will also do a new release in Moodle's plugins repository.

Best, Kathrin

**Comment by pkgh** [comment]
OK, thanks a lot. Looking forward to that :) .
Best,
Przemek

**Comment by Kathrin84** [comment]
Here's the patch: https://github.com/moodleuulm/moodle-local_resort_courses/commit/6d5a630a2a07be7455ae215c15edf56b7fa00228

The new release in the plugins repository will follow directly.

So, I will close this issue as fixed.
