### ISSUE TITLE
skipcategories has wrong default value

### ISSUE THREAD

**Issue by ewallah** [moodleuulm/moodle-local_resort_courses#6]
The local_resort_courses/skipcategories setting is skipped.

Steps to detect the error:

1. Install plugin
2. Initialize behat
3. Test the admin_bookmarks block using vendor/bin/behat -- blocks/admin_bookmarks/tests/behat/bookmark_admin_pages.feature 

Expected result: 3 scenarios (3 passed) 28 steps (28 passed)
Actual result:  3 scenarios (1 passed, 2 failed) 28 steps (21 passed, 2 failed, 5 skipped)

The 2 failures are related to a not yet stored skipcategories setting: 

![capture_001_08032020_154144](https://user-images.githubusercontent.com/1324161/76165240-af563b80-6155-11ea-909e-f48487e4dfbd.png)

**Comment by abias** [comment]
Thanks for highlighting this issue, @ewallah .

I think I was able to fix it within https://github.com/moodleuulm/moodle-local_resort_courses/commit/833999260f9e7231c6c69d7ec6100085d3a89c4d.
