### ISSUE TITLE
Regularly sorting courses using cron

### ISSUE THREAD

**Issue by ohameiri** [moodleuulm/moodle-local_resort_courses#7]
Hi
do you think it would be possible to add this ?
or maybe have a CLI script that i  would be able to run each time i want to sort everything ?

**Comment by abias** [comment]
Hi @ohameiri ,

thank you for this proposal.
This has been implemented in https://github.com/moodleuulm/moodle-local_resort_courses/commit/8cf4b55ce6e660b16bef99d1f1f14cdd0847b178 as scheduled task which is disabled by default.

Have fun!
Alex

**Comment by ohameiri** [comment]
Amazing
thanks !
